NSM-1
frontend-park-mail-ru/2021_1_Noskool-team pull request #12
Opened 2021-04-06 15:29 UTC by lerakrya8

2021-04-06 15:58 UTC, CUzkov requested changes

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/HeaderButtons.tsx
>                  <div id={ID_NAVMENU} class={PROFILE_CLASS}>
а зачем тут id?

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +        // justify-content: space-between;
удолить

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +      ul {
закнинь это в главный style.scss

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +  form {
закнинь это в главный style.scss

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +        border-bottom: 1px solid #8a8c99;
цвета в переменные все нужно

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +          color: #8a8c99;
цвета в переменные все нужно

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +    box-shadow: 5px 5px 5px 5px rgba($color: #8a8c99, $alpha: 0.3);
цвета в переменные все нужно

2021-04-06 15:58 UTC, CUzkov commented on src/components/HeaderButtons/style.scss
> +    color: #8a8c99;
цвета в переменные все нужно

2021-04-06 15:58 UTC, CUzkov commented on src/components/ProfileButtons/ProfileButtons.tsx
> +            <li class='item' key={index}>
ключ не нужон

2021-04-06 15:58 UTC, CUzkov commented on src/components/RightMenu/RightMenu.tsx
> +            <li class='item' key={index}>
ключ не нужен

2021-04-06 15:58 UTC, CUzkov commented on src/components/RightMenu/style.scss
> +ul {
аналогично в главный style.scss

2021-04-06 15:58 UTC, CUzkov commented on src/components/RightMenu/style.scss
> +      // mask-image: url(icons/repeat.svg);
удоли

2021-04-06 15:58 UTC, CUzkov commented on src/components/RightMenu/style.scss
> +      // mask-image: url(icons/repeat.svg);
и комменты ниже тоже

2021-04-06 15:58 UTC, CUzkov commented on src/types/rightMenu.ts
> +export interface RightMenu {
все интерфейсы, не связанные с запросами и стором нужно прописывать прям в компоненте после импортов

2021-04-06 15:58 UTC, CUzkov commented on src/types/rightMenu.ts
> +export interface RightMenu {
проверь все типы свои

2021-04-06 15:58 UTC, CUzkov commented on src/utils/router-comp.tsx
> +                {/* <div class={pageWrapper('content', 'player')}>
удолить или TODO добавить

2021-04-06 15:58 UTC, CUzkov commented on src/utils/style.scss
> +      // left: 0;
удолить

2021-04-06 15:58 UTC, CUzkov commented on src/utils/style.scss
> +      // right: 0;
и ито удолить

2021-04-08 13:21 UTC, lerakrya8 commented on src/components/HeaderButtons/style.scss
> +      ul {
done

2021-04-08 13:22 UTC, lerakrya8 commented on src/components/HeaderButtons/style.scss
> +  form {
done

2021-04-08 13:22 UTC, lerakrya8 commented on src/components/RightMenu/style.scss
> +      // mask-image: url(icons/repeat.svg);
done

2021-04-08 17:11 UTC, lerakrya8 commented on src/components/HeaderButtons/HeaderButtons.tsx
>                  <div id={ID_NAVMENU} class={PROFILE_CLASS}>
done

2021-04-08 17:11 UTC, lerakrya8 commented on src/components/HeaderButtons/style.scss
> +        // justify-content: space-between;
done

2021-04-08 17:12 UTC, lerakrya8 commented on src/utils/style.scss
> +      // left: 0;
done

2021-04-08 17:12 UTC, lerakrya8 commented on src/utils/style.scss
> +      // right: 0;
done

2021-04-08 17:20 UTC, lerakrya8 commented on src/types/rightMenu.ts
> +export interface RightMenu {
done

2021-04-08 17:24 UTC, lerakrya8 commented on src/components/HeaderButtons/style.scss
> +        border-bottom: 1px solid #8a8c99;
done

2021-04-09 17:02 UTC, merged